{% set version = "2.4" %}
{% set variant = "openblas" %}

package:
  name: optpp
  version: {{ version }}

source:
  fn: optpp-{{ version }}.tar.gz
  url: https://software.sandia.gov/opt++/downloads/optpp-{{ version }}.tar.gz
  sha256: 7a0c8ba5e15d5e74f94b08f5dc65a13d64d2f7bbd1acbc153c09dd2425eb66cd
  patches:
    # FTBFS on libc++ (osx)
    - limits.patch
    # missing linking to newmat, blas
    - link_libs.patch

build:
  number: 1200
  features:
    - blas_{{ variant }}  # [not win]
  # msvc is unsupported, but maybe we can add a custom cmake script later
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - autoconf  # [unix]
    - automake  # [unix]
    - libtool  # [unix]
    - make  # [unix]
  host:
    - blas 1.1 {{ variant }}  # [not win]
    - openblas
  run:
    - blas 1.1 {{ variant }}  # [not win]
    - openblas

test:
  commands:
    - test -f ${PREFIX}/include/opt++/Opt.h  # [unix]
    - if not exist %PREFIX%\\Library\\include\\opt++\\Opt.h exit 1  # [win]
    - conda inspect linkages -p ${PREFIX} optpp  # [not win]
    - conda inspect objects -p ${PREFIX} optpp  # [osx]

about:
  home: https://software.sandia.gov/opt++/
  license: LGPL
  license_file: COPYRIGHT
  summary: An Object-Oriented Nonlinear Optimization Library

extra:
  recipe-maintainers:
    - jschueller
