travis:
  secure:
    BINSTAR_TOKEN: Ub/rKL2vqeqt1jn4z3cUf16b1MxIgP24HQUeAXC9ZKYFMmzwm5eVsfK/47Gedcz3abk91hqt5ULYEDwqY4ep65EtQdKXZ2UQZWK5ckLzbBXW/3VhVLvikbb7kpo3TROR+GIPCsGPzP07niXGMMkAdc93LkTgmSodbLSRYV3WUkryNtxzzwksx1bHHYa7We8cl8io+qAgMPq2gixg2pGi19x1fCfaxR13VuIHXlsuLlZJAZagUTVX83YwDqnQTDWN/OMIlOrpZEGevNarGEQl0F76tC/O52HslqO1B/+hxZxlCor+mwQJ4azKzEp+y1SygG0JVPwtasOHDGBPMVo4ZxEId3kJuL3TcNopVjEHkVWVehqyW4H83MhJXnyvQVB3Ursfu75Syyo5+MUCCYcU+pAvgLR9UtoVvA2dKxNSgCRvezggaQ4tYvJzt7P17ZHI/RCtRdNYtxyBzm5HDUFkGGX//Ob/F+YtT8Fw7CMjcPGiz9HSZ/tyzYTgG2QOI515fNuHG1MSkk4Ry2NQTR56AO5kEGe84ygqhA9MY76cSLNcBWnipywvw3TU1mS5c9uz5WeeK4Z9zMSpfyo5uJDrJq2c1keUemTyuyOjjIOCpkQ+0jAK51xHKDZ5Vo7JOsuTkxjFcOyv7YAzGLsdp1GIzw2cE4dnqoM4zcTCXEra048=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
